### ISSUE TITLE
On the list block the alignment cant be changed in the editor

### ISSUE THREAD

**Issue by SophieAmnesty** [amnestywebsite/humanity-theme#10]
The list block has no options to change the alignment to left or right aligned. This causes problems for text in Arabic, which is right aligned and for English text, in the wider format 'component template' pages, which is left aligned. 

**To Reproduce**
1. Create post
2. Set to component template 
3. insert text, including list 
4. align paragraph blocks to the left
5. you will see the list block are now out of alignment with the rest of the text 

**Expected behaviour**
Option to align the list block should be available in the block formatting options. 

**Actual behaviour**
No options to align the list block.

**Link to a page where the bug is reproduced in isolation**
https://isaidotorgstg.wpengine.com/en/latest/news/2022/05/list-block-alignment-en-ar/

**Which site is this happening on**
amnesty.org

**Link to a page in the documentation site where the feature is described**
https://wordpresstheme.amnesty.org/administration/visual-regression-tests/list/

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/109

**Comment by AmnestyAM** [comment]
Does this look right to you @SophieAmnesty I didn't see the original image but when I follow the steps its looks ok on STG

https://isaidotorgstg.wpengine.com/en/latest/news/2024/04/test-am/

**Comment by SophieAmnesty** [comment]
Hey, yeah I think it's ok except if I apply the 'align left' (rather than 'none') to the list block it now goes too far left: 
![image](https://github.com/amnestywebsite/humanity-theme/assets/99269799/c514052a-f723-4151-95b4-19d31d45703d)

Did we get rid of the 'none' alignment option on other blocks when we did the template work last year? 

Paragraph just has left, centre, right: 
![image](https://github.com/amnestywebsite/humanity-theme/assets/99269799/70555aa4-2048-407f-939a-d05a0858fd9c)
 

Do you think we should stick with those three and make sure the 'left' one lines up with the paragraph rather than dropping back?

**Comment by jaymcp** [comment]
> Did we get rid of the 'none' alignment option on other blocks when we did the template work last year?

this is standard core behaviour now, i believe. instead of a "none" option, now it's a matter of selecting the current alignment again to remove it. so if alignment is set centred, choosing centred again from the dropdown will remove the alignment.

**Comment by jaymcp** [comment]
we'll action that as part of this issue, so i'm going to put this back into todo, and move it out of the RC.

FYI @Gentyspun

**Comment by Gentyspun** [comment]
Same PR/Branch: https://github.com/amnestywebsite/humanity-theme/pull/109

Was a margin-left: 0; overriding another margin, should be good now

**Comment by AmnestyAM** [comment]
LGTM on STG -> https://isaidotorgstg.wpengine.com/en/latest/news/2024/05/test-for-10/
BTW my UI looks like this on STG, cleared the cache on WPE, hard refreshed, also looked the same in Chrome and Edge 
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/629c4868-694d-4992-9476-01b3e80eaa9b)
https://wordpress.org/documentation/article/list-block/

**Comment by jaymcp** [comment]
that's very strange. it's showing you the text fallbacks for the icons, but the link icon is still there. all of those come from core, and i'm not experiencing the same issue, so i can't understand why that's happening. we can perhaps figure it out on a call?
