### ISSUE TITLE
Release Candidate - Sprint 97, 98

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#114]
## Tickets slated for release  

- https://github.com/amnestywebsite/humanity-theme/issues/116
- https://github.com/amnestywebsite/humanity-theme/issues/22
- https://github.com/amnestywebsite/humanity-theme/issues/33
- https://github.com/amnestywebsite/humanity-theme/issues/99
- https://github.com/amnestywebsite/humanity-theme/pull/100
- https://github.com/amnestywebsite/humanity-theme/pull/118
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2388 trigger full width menu and hide burger at 1024px 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2586 adds a 40 px gutter to the content area 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2685 removed an unnecessary page option  
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2698 fixed some spacing issues on the header block 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2780 made it easier to edit title and tags on post list block 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2786 fixed margin on links with icon block 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2833 better lag support for ZH 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2853 removed feature / header images from showing twice 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2884 fixed the size options on header block

Internal Issues 

- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2390
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2512 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2555 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2595 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2659
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2851 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2892
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2893
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2895
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2896
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2897
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2898
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2902
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2819

## Automated tests  
- [x] GhostInspector tests run as expected
- [ ] New GhostInspector tests tickets created (if needed)

## Checks  
- [ ] List any new translation strings 
- [ ] Verify new code meets WCAG standards
- [ ] Verify L2R and R2L 
- [ ] Document for anything new/changed

## Version number  
- Theme: `v1.0.1`
- Branding: `v1.0.1`
- SP Runner: `v2.1.0`
- Theme Companion: `v2.2.0`

## Scheduled release date  
- Thursday 11th April 2024

**Comment by jaymcp** [comment]
Removing the following from the RC, as issues were uncovered during final testing that need rectifying prior to release. More information can be found in the ticket(s):
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2876

**Comment by AmnestyAM** [comment]
Looks good to me - signed off

**Comment by jaymcp** [comment]
@AmnestyAM apologies; I missed https://github.com/amnestywebsite/amnesty-wp-theme/issues/2819 from the RC. Would you be okay to take a quick look this afternoon? We can then add it to the release tomorrow. Thanks

**Comment by AmnestyAM** [comment]
I added some notes for the general public, hopefully in future I can move the issues to the right repo before we work on them

**Comment by AmnestyAM** [comment]
also approved with https://github.com/amnestywebsite/amnesty-wp-theme/issues/2896 (setting the AIR Location single templates to match our other templates)

**Comment by jaymcp** [comment]
Code release is complete. Slack thread: https://bigbite.slack.com/archives/CBLHK14G7/p1712742816586809

https://github.com/amnestywebsite/amnesty-wp-theme/issues/2833 is the last item to do

**Comment by jaymcp** [comment]
https://github.com/amnestywebsite/amnesty-wp-theme/issues/2833 has now been completed, so i am going to close this release as complete.
