### ISSUE TITLE
Epic - Core WP Update - Navigation + Quote 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#122]
Switch to core WP navigation support and the in page menu https://wordpress.org/documentation/article/navigation-block/ https://wordpresstheme.amnesty.org/blocks/c010-menu/ hide existing (1)
Migrate to Core WP quote (3)

### Sprints allocated 
Number of sprints: 1
Link to sprint if known: TBC

## Goals 
- [x] #314
- [x] #315
- [x] #316
- [x] #317

**Comment by BBTomA** [comment]
@jaymcp closed, feel free to re-open
