### ISSUE TITLE
Epic - Core WP Update - Cover Block + Basic Audio block 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#123]
Switch background media https://wordpresstheme.amnesty.org/blocks/b054-background-media/ to cover block https://wordpress.org/documentation/article/cover-block/ (big to migrate as used a lot)
Basic Audio block (before or after quote with alignment controls) - https://wordpress.org/documentation/article/audio-block/ (1)

### Sprints allocated 
Number of sprints: 1 

## Goals  

- [x] #260
- [ ] #264
- [x] #262
- [x] #263
- [x] #261

## notes

- still support section

- sql for finding background media instances:
```sql
select id, post_title, guid
from wp_posts
where post_type in ('post', 'page')
and post_status = 'publish'
and post_content like '%<!-- wp:amnesty-core/background-media%'
order by id desc
```

**Comment by BBTomA** [comment]
@jaymcp closed, feel free to re-open
