### ISSUE TITLE
Epic - Refactor Links with icons block

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#132]
### Discussed in https://github.com/amnestywebsite/humanity-theme/discussions/19

<div type='discussions-op-text'>

<sup>Originally posted by **AmnestyAM** February  6, 2024</sup>
We had a lot of small issues with this block and an overhaul is probably due.
https://github.com/amnestywebsite/amnesty-wp-theme/issues/2373 </div>

### Sprints allocated 
Number of sprints: 1
Link to sprint if known: TBC

## Goals 
- [x] #120 [comment](https://github.com/amnestywebsite/humanity-theme/issues/120#issuecomment-2149987575)
- [x] #181  
- [x] #208

**Comment by carolinejcourtney** [comment]
Is this a duplication with https://github.com/amnestywebsite/humanity-theme/issues/143 ? @AmnestyAM

**Comment by AmnestyAM** [comment]
unfortunately not, the other ticket is to move the code from one part of the code base to another, a much small task

**Comment by AmnestyAM** [comment]
https://isaidotorgdev.wpengine.com/en/latest/news/2024/06/am-pattern-test-full/ 

![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/613e14cf-dca3-4a79-968d-2d5479ae91b7)


I was able to replicate this but it was quite tricky 

- 2 columns 
- 2 x 2 columns in each to get 4 columns
- Thumnnail select for image
- no credit, no caption
- removed the captions under the image 
- set links to light 

Maybe having a 4 column pattern would make it a bit easier?

**Comment by jaymcp** [comment]
> Maybe having a 4 column pattern would make it a bit easier?

that will be actioned as part of introducing the LWI patterns, as discussed in a call, tracked in this ticket: https://github.com/amnestywebsite/humanity-theme/issues/181
