### ISSUE TITLE
Bug - Iframe block does not show when used in a sidebar 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#139]
**Describe the bug**  
when adding an iframe block into the side bar you need to specify the width to get the block to show, the UI says only a height is required, I needed to add both a height and a width.  

**To Reproduce**  
1. Add a post
2. Add a side bar
3. Add the side bar to a post 
4. Add a iframe to the sidebar
5. add only a height to the iframe
6. the iframe does not render 

**Expected behaviour**  
either the ui should be accurate and tell the user they need to add a width if using in a side bar or the block should show without having to add a width 

**Actual behaviour**  
the block does not render, seems to set a min width but not a max width 

**Link to a page where the bug is reproduced in isolation (optional)**  
URL so we can quickly see the issue 

**Screenshots**  
when caption added
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/97c47074-07e6-4b38-9992-778b9cd45496)
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/b774c2ed-bc72-4fe6-b1f6-a948cfb4b4b6)

**Comment by AmnestyAM** [comment]
I have tried adding non breaking spaces and a white jpg to open up the space neither worked

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/140
