### ISSUE TITLE
FSE Recipients

### ISSUE THREAD

**Issue by BBTomA** [amnestywebsite/humanity-theme#144]
Full Site Editing requires blocks to be a combination of JS and PHP.

Rework the block so that it renders in PHP

**Comment by Gentyspun** [comment]
As part of this ticket, I have removed the Recipient block from the theme and added it to the branding plugin

THEME PR: https://github.com/amnestywebsite/humanity-theme/pull/156

PLUGIN PR: https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/14
