### ISSUE TITLE
Release Candidate - Sprint 100-102

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#161]
## Tickets slated for release  
- https://github.com/amnestywebsite/humanity-theme/issues/91
- https://github.com/amnestywebsite/humanity-theme/pull/166
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2908
- https://github.com/amnestywebsite/humanity-theme/pull/197
- https://github.com/amnestywebsite/humanity-donations/pull/1
- https://github.com/amnestywebsite/humanity-donations/pull/2
- https://github.com/amnestywebsite/humanity-theme/pull/204
- https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/18
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2940
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2573
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2912

## Automated tests  
- [x] GhostInspector tests run as expected
- [ ] New GhostInspector tests tickets created (if needed)

## Checks  
- [ ] List any new translation strings 
- [ ] Verify new code meets WCAG standards
- [ ] Verify L2R and R2L 
- [ ] Document for anything new/changed

## Version number  
- Theme: [`v1.0.3`](https://github.com/amnestywebsite/humanity-theme/pull/233)
- Donations: [`v1.0.1`](https://github.com/amnestywebsite/humanity-donations/pull/4)
- Branding: [`v1.0.5`](https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/27)
- Parastoo Font: [`v2.0.1`](https://github.com/amnestywebsite/wp-plugin-parastoo-font/pull/4)

## Scheduled release date  
- Tuesday 4th June 2024

**Comment by jaymcp** [comment]
@AmnestyAM release PRs have been created. Are you happy to sign off this RC for release today?

**Comment by AmnestyAM** [comment]
LGTM thanks

**Comment by jaymcp** [comment]
Release complete. Slack thread: https://bigbite.slack.com/archives/CBLHK14G7/p1717582644196299
