### ISSUE TITLE
Pattern - Full - Chunky heading with links (rqd for web report)

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#171]
https://github.com/amnestywebsite/amnesty-wp-theme/issues/2932
https://wordpresstheme.amnesty.org/patterns-web-report/
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/dcfa94f7-5dae-4c9e-af34-5e7e3956c419)

think about space on right hand side, do we include in the pattern or exclude

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/188

**Comment by AmnestyAM** [comment]
added one here and it LGTM https://isaidotorgdev.wpengine.com/en/latest/news/2024/06/am-test-web-report/
