### ISSUE TITLE
Pattern - 66-33 - Text with image (rqd for PR+)

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#173]
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/7d4ff3a7-4532-4aa9-a0ff-b34d7591988e)
https://wordpresstheme.amnesty.org/patterns-press-release-plus/
https://github.com/amnestywebsite/amnesty-wp-theme/issues/2933

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/191

**Comment by AmnestyAM** [comment]
LGTM https://isaidotorgdev.wpengine.com/en/latest/news/2024/06/am-test-pr/
