### ISSUE TITLE
Pattern - 66-33 - Text with video (rqd for PR+)

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#174]
used in PR+ but not in block template

https://github.com/amnestywebsite/amnesty-wp-theme/issues/2933

![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/2659f7bb-b6fc-40fe-9c90-0a047ea533e0)

I need to work out what to do with this block as the examples has the page title...

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/192/files

**Comment by AmnestyAM** [comment]
This pattern does not add the heading to the block, there might be a reason for this, if so let me know :-) Thanks 

![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/648b3c8a-6875-43dd-8362-120cfe3c8b1b)

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/247
