### ISSUE TITLE
Pattern - 66-33 - Text with key facts

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#175]
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/b8e2efdd-8277-4c48-b605-a551bb5ae499)

used in PR+ but not in block template 
https://wordpresstheme.amnesty.org/pattern-press-release-plus-section-with-facts/

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/187

**Comment by AmnestyAM** [comment]
LGTM here -> https://isaidotorgdev.wpengine.com/en/latest/news/2024/06/am-test-web-report/
