### ISSUE TITLE
Pattern - 50-50 - Text with video (rqd for issue)

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#177]
used on this block template https://github.com/amnestywebsite/amnesty-wp-theme/issues/2935

https://wordpresstheme.amnesty.org/patterns-issue-page/

![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/ec911eba-7421-4b92-9129-edb670976367)

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/194

**Comment by AmnestyAM** [comment]
LGTM here https://isaidotorgdev.wpengine.com/en/am-test-issue/
