### ISSUE TITLE
Pattern - Full - Image with buttons

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#178]
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/a596ce3a-dd9f-4e66-b862-b68f8cea4697)
https://wordpresstheme.amnesty.org/patterns-image-with-buttons/

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/195

**Comment by AmnestyAM** [comment]
LGTM https://isaidotorgdev.wpengine.com/en/latest/news/2024/06/am-pattern-test-full/ Thanks
