### ISSUE TITLE
Pattern - Full - Case Study

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#179]
https://wordpresstheme.amnesty.org/patterns-case-study/
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/e74209d3-02e6-4fdb-84b2-ab89271480c5)

Variation white

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/196

**Comment by AmnestyAM** [comment]
I guess its the same as the 50/50 with the image on the left - LGTM https://isaidotorgdev.wpengine.com/en/latest/news/2024/06/am-pattern-test-full/
