### ISSUE TITLE
Pattern - Full or 33-33-33 - 3 X CTA (used on get involved)

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#180]
https://wordpresstheme.amnesty.org/patterns-get-involved/
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/a55574f8-d75f-44ca-85e5-bb66714291c3)

**Comment by AmnestyAM** [comment]
I might re work this just to be the 3 boxes

**Comment by AmnestyAM** [comment]
I was kind of on the fence, I feel the 3 columns might be a more useful and reusable pattern so I am leaning that way. Any thoughts @SophieAmnesty ?

**Comment by AmnestyAM** [comment]
@Gentyspun looks like you did the PR already so don't mind living with either

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/200

**Comment by AmnestyAM** [comment]
I was able to add this 
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/b2e909df-3447-4547-85bc-f082694308a1)

But it required me adding padding to the block, to stop the text touching the black border,

**Comment by AmnestyAM** [comment]
should we add the padding on the P in the pattern?

**Comment by AmnestyAM** [comment]
not sure what I was re testing but the text is still touching the edges of the box 

![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/866efaa5-e98e-4d86-a8f8-6d725965cf17)

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/258

**Comment by AmnestyAM** [comment]
LGTM 

![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/a9912209-857d-400c-98dd-ef49cf9fe5fb)
