### ISSUE TITLE
Pattern - Links with icons - group with border and some other fancy stuff

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#181]
- [x] LWI x 1
- [x] LWI Square x 1
- [x] LWI x 3
- [x] LWI Square x 3
- [x] LWI x 4
- [x] LWI Square x 4

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/200

**Comment by AmnestyAM** [comment]
I was able to replicte this 
https://www.amnesty.org/en/what-we-do/
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/3e3e2205-73a2-4201-899c-56bdae0c4b69)

https://isaidotorgdev.wpengine.com/en/latest/news/2024/06/am-pattern-test-full/
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/8d3ee7cc-f513-4d42-9311-d7a4f5f51f0e)

I had to create two columns then put two columns in each two columns to give me 4 columns

- Then I set the Heading to H3
- Set the image thumbnail to retina
- Link to light

Can we discuss in the stand up, seems like we can get something to work here but might need a little refinement

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/242

**Comment by AmnestyAM** [comment]
could do with some padding  to stop the text touching the border 

![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/8fff73b2-834b-4658-bcbd-63fb82a0e5a9)
