### ISSUE TITLE
Patterns UI - Rename Amnesty Core

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#182]

**Comment by AmnestyAM** [comment]
not sure what I am testing here but I see this

![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/86a01c30-8223-41f2-8fb1-5825b80c2bc5)

It might be passing if it was something else?

**Comment by jaymcp** [comment]
That's the category for blocks; this ticket relates to patterns.
We definitely should open a separate ticket for addressing block categorisation, though

**Comment by jaymcp** [comment]
New issue opened for the block categorisation: https://github.com/amnestywebsite/humanity-theme/issues/257

**Comment by AmnestyAM** [comment]
ahhh sorry! Thanks
