### ISSUE TITLE
Patterns UI - group patterns into logical categories

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#184]
consider groups of patterns and blocks such as full, 66, 50 for size or another such as content type like actions, image, text etc

**Comment by jaymcp** [comment]
@AmnestyAM could you provide some info on this one, please?

**Comment by AmnestyAM** [comment]
Hi @jaymcp updated so this sound make sense now

**Comment by jaymcp** [comment]
thanks @AmnestyAM !

**Comment by AmnestyAM** [comment]
After using this a little bit now I think a 66,33 category might help as I think people will either look for the number of columns or the column sizes, as if a user is seeing 50,50 and 1/3 1/3 1/3 they might expect to also see 2/3 1/3 as we have those too. 

What do you think?

**Comment by jaymcp** [comment]
Sure. I've added in a `2/3, 1/3` category. You can see this on DEV now.

**Comment by AmnestyAM** [comment]
LGTM 

![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/21a3883a-e414-4bc1-8521-76b6f3fd81f9)
