### ISSUE TITLE
Pattern - full - Evergreen Text Highlight

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#186]
https://wordpresstheme.amnesty.org/patterns-top-section/
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/5e73da0c-2ab5-42f0-9d81-9c5e997ae11b)

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/207

**Comment by AmnestyAM** [comment]
LGTM thanks :-) https://isaidotorgdev.wpengine.com/en/latest/news/2024/06/am-pattern-test-full/
