### ISSUE TITLE
On the header block the featured image copyright credit shows when using video 

### ISSUE THREAD

**Issue by SophieAmnesty** [amnestywebsite/humanity-theme#2]
**Describe the bug**
When I add a video to the header block, the block doesn't show the copyright credit from the video. Instead the copyright credit from the featured image shows. 

**To Reproduce**
1. add a new post
2. add a header block, select 'video' background type and add a video 
3. add a featured image as well 
4. preview post and see featured image copyright credit showing over the video.

**Expected behaviour**
When users see the video they should see the correct copyright credit. 

**Actual behaviour**
The wrong copyright credit is showing on the video.

**Link to a page where the bug is reproduced in isolation**
https://isaidotorgstg.wpengine.com/en/latest/news/2024/01/header-block-video-copyright-credit/

**Which site is this happening on**
www.amnesty.org 

**Link to a page in the documentation site where the feature is described**
https://wordpresstheme.amnesty.org/blocks/b000-header/

**Screenshots**
![image](https://github.com/amnestywebsite/amnesty-wp-theme/assets/99269799/1b35b84c-264c-4d28-8947-62f701047c4e)
![image](https://github.com/amnestywebsite/amnesty-wp-theme/assets/99269799/06adb4a7-2e65-4000-9e0c-a432b536772d)

**Desktop (please complete the following information):**
https://www.whatsmybrowser.org/b/EPIA9

**Comment by Gentyspun** [comment]
Created PR: https://github.com/amnestywebsite/humanity-theme/pull/95

**Comment by Gentyspun** [comment]
@AmnestyAM I'm just double checking should the video credit ALWAYS be displayed?

Currently on the Header Block if the type is changed to "video" we remove the toggles to hide the image credit and caption. This could imply that video credits should always show, or never show. Just want to clarify which it is

**Comment by AmnestyAM** [comment]
Hi @Gentyspun My guess is if video was select we would ideally they would have the same option but "hide video credit" "hide video caption" or have the option for but but have "hide media caption" "hide media credit".

I think if the user have selected a video they would expect the credit and caption to come from the video, and if image is selected the credit and caption to come from the image. 

Did this help?

**Comment by AmnestyAM** [comment]
I see the copyright https://isaidotorgstg.wpengine.com/en/latest/news/2024/06/hero-block/ LGTM
