### ISSUE TITLE
Pattern - Social Share

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#201]
### Discussed in https://github.com/amnestywebsite/humanity-theme/discussions/199

<div type='discussions-op-text'>

<sup>Originally posted by **jaymcp** May 13, 2024</sup>
The existing Social Share block pattern default content uses Amnesty's social links, and a (now removed) YouTube video embed.
Now that the theme is open source, we should probably either remove this pattern from the theme, or update the default content to something generic.

Possibly worth addressing alongside https://github.com/amnestywebsite/humanity-theme/issues/120?</div>

**Comment by jaymcp** [comment]
PRs created to
a) remove the pattern from the theme, and
b) to add support for patterns to the branding plugin, and introduce the pattern there.

**Comment by AmnestyAM** [comment]
LGTM thanks https://isaidotorgdev.wpengine.com/en/latest/news/2024/06/am-pattern-test-full/
