### ISSUE TITLE
Block restrictions

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#205]
When creating the Humanity Theme, we did not remove the block restrictions we had in place.
Whilst we don't officially support the restricted blocks, we should not prevent users from using them if they so choose. We should migrate these restrictions into a plugin.

**Comment by AmnestyAM** [comment]
I could actually imagine that being a popular plugin in the WP repo

**Comment by AmnestyAM** [comment]
I read my above comment and it made no sense, I meant to say I could imagine a hide block plugin could be popular.

**Comment by jaymcp** [comment]
> I read my above comment and it made no sense, I meant to say I could imagine a hide block plugin could be popular.

Could be, if done right! :)
