### ISSUE TITLE
Release Candidate - Full Site Editing Support

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#218]
## Tickets slated for release  

**NB:** Issue(s) listed under multiple headings indicate that a PR to that target covers part of the work involved in completing the issue

### Humanity Theme
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/1070 Refactor header and footer block to a single hero block
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2739 Basic FSE support 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2871 Fixed styling issues between Humanity theme and AI branded plugin 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2916 Gutters added to all templates 
- https://github.com/amnestywebsite/humanity-theme/issues/2 
- https://github.com/amnestywebsite/humanity-theme/issues/6
- https://github.com/amnestywebsite/humanity-theme/issues/8
- https://github.com/amnestywebsite/humanity-theme/issues/10
- https://github.com/amnestywebsite/humanity-theme/issues/120
- https://github.com/amnestywebsite/humanity-theme/issues/144
- https://github.com/amnestywebsite/humanity-theme/issues/171
- https://github.com/amnestywebsite/humanity-theme/issues/172
- https://github.com/amnestywebsite/humanity-theme/issues/173
- https://github.com/amnestywebsite/humanity-theme/issues/174
- https://github.com/amnestywebsite/humanity-theme/issues/175
- https://github.com/amnestywebsite/humanity-theme/issues/176
- https://github.com/amnestywebsite/humanity-theme/issues/177
- https://github.com/amnestywebsite/humanity-theme/issues/178
- https://github.com/amnestywebsite/humanity-theme/issues/179
- https://github.com/amnestywebsite/humanity-theme/issues/180
- https://github.com/amnestywebsite/humanity-theme/issues/181
- https://github.com/amnestywebsite/humanity-theme/issues/182
- https://github.com/amnestywebsite/humanity-theme/issues/184
- https://github.com/amnestywebsite/humanity-theme/issues/186
- https://github.com/amnestywebsite/humanity-theme/issues/201
- https://github.com/amnestywebsite/humanity-theme/issues/205
- https://github.com/amnestywebsite/humanity-theme/issues/225
- https://github.com/amnestywebsite/humanity-theme/issues/228
- https://github.com/amnestywebsite/humanity-theme/issues/229
- https://github.com/amnestywebsite/humanity-theme/issues/243
- https://github.com/amnestywebsite/humanity-theme/pull/216
- https://github.com/amnestywebsite/humanity-theme/pull/222
- https://github.com/amnestywebsite/humanity-theme/pull/250
- https://github.com/amnestywebsite/humanity-theme/pull/268
- https://github.com/amnestywebsite/humanity-theme/pull/271

### [Humanity Donations](https://github.com/amnestywebsite/humanity-donations)
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2916 Gutters added to all templates 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2739 Basic FSE support 

### [Humanity Petitions](https://github.com/amnestywebsite/humanity-petitions)
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2739 Basic FSE support 
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2916 Gutters added to all templates 

### Amnesty Branding (Internal)
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2739
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2871
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2916
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2932
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2933
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2934
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2935
- https://github.com/amnestywebsite/humanity-theme/issues/144
- https://github.com/amnestywebsite/humanity-theme/issues/201
- https://github.com/amnestywebsite/humanity-theme/issues/205
- https://github.com/amnestywebsite/humanity-theme/issues/208
- https://github.com/amnestywebsite/humanity-theme/issues/225
- https://github.com/amnestywebsite/humanity-theme/issues/228
- https://github.com/amnestywebsite/wp-plugin-amnesty-branding/issues/24 branded the gallery block for AI branded plugin 
- https://github.com/amnestywebsite/wp-plugin-amnesty-branding/issues/25
- https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/19
- https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/22

### PF (Internal)
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2739

### SP (Internal)
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2916

### TC (Internal)
- https://github.com/amnestywebsite/amnesty-wp-theme/issues/2916

## Automated tests  
- [ ] GhostInspector tests run as expected
- [ ] New GhostInspector tests tickets created (if needed)

## Checks  
- [ ] List any new translation strings 
- [ ] Verify new code meets WCAG standards
- [ ] Verify L2R and R2L 
- [ ] Document for anything new/changed

## Version number  
- Theme: `v1.1.0`
- Donations: `v1.1.0`
- Petitions: `v1.1.0`
- Branding (Internal): `v1.1.0`
- PF (Internal): `v3.0.0`
- SP (Internal): `v2.1.3`
- TC (Internal): `v2.2.3`

## Scheduled release date  
- Thur 4th July 2024

**Comment by jaymcp** [comment]
Yeah we're hoping to include it

**Comment by AmnestyAM** [comment]
LGTM - Approved thanks everyone :-)

**Comment by jaymcp** [comment]
Release complete. Slack thread https://bigbite.slack.com/archives/CBLHK14G7/p1720001483436269
