### ISSUE TITLE
On the "updated at" date feature in the editor we cant remove the date once added

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#22]
**Describe the bug**
If I accidentally add a 'updated at' date to a post I can't take it off again. 

e.g. https://www.amnesty.org/en/latest/news/2023/04/turkiye-people-with-disabilities-neglected-in-humanitarian-response-to-devastating-earthquake/ 

**or maybe I just don't know how to?**

**To Reproduce**
1. add new post
2. click on 'choose date' next to 'updated at' in the post settings
3. select a date
4. publish
5. See post had published date and updated date 
6. go back to edit the post and try to remove the updated date 
7. can't do it! 

**Expected behaviour**
should be able to undo the updated at date in case it was selected by accident. 

**Actual behaviour**
once you've added an updated at date you can't take it off again

**Link to a page where the bug is reproduced in isolation**
https://isaidotorgstg.wpengine.com/en/latest/news/2023/04/updated-time-stamp-test/

**Which site is this happening on**
amnesty.org 

**Desktop (please complete the following information):**
 https://www.whatsmybrowser.org/b/AZ83C

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/10

**Comment by AmnestyAM** [comment]
LGTM
