### ISSUE TITLE
Re-enable the `core/details` block, and deprecate the `amnesty-core/collapsable` block

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#228]

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/238

**Comment by jaymcp** [comment]
@AmnestyAM is this one approved? i see it's moved column, but it doesn't have the label, so i just want to double check before i close it. thanks

**Comment by AmnestyAM** [comment]
LGTM
