### ISSUE TITLE
Ensure the `core/details` block matches the `amnesty-core/collapsable` block visually

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#231]
As we are deprecating the `amnesty-core/collapsable` block in favour of the `core/details` block in https://github.com/amnestywebsite/wp-plugin-amnesty-branding/issues/26, we should ensure that the UI retains a similar appearance.

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/240
