### ISSUE TITLE
Create audio + quote block patterns

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#261]
- [x] stacked audio + quote 
- [x] stacked quote + audio
- [x] stacked audio + details (titled "Transcript")

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/269

**Comment by AmnestyAM** [comment]
Looks good, what do you think @SophieAmnesty

**Comment by SophieAmnesty** [comment]
yeah looks good! thanks :)
