### ISSUE TITLE
Support core Cover block

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#262]
- [x] Enable the block: https://github.com/amnestywebsite/wp-plugin-amnesty-branding/issues/34
- [x] Check that its styles match the theme's design

**Comment by Gentyspun** [comment]
Theme PR: https://github.com/amnestywebsite/humanity-theme/pull/259

**Comment by AmnestyAM** [comment]
nice stuff again!!

In the theme companion can we / should we cull the non Amnesty colors? thoughts? 

![Image](https://github.com/user-attachments/assets/8874032c-35c3-401b-b376-9f6bf0030ad1)

![Image](https://github.com/user-attachments/assets/a57ff100-03ce-4c8c-8b5a-385de904d1a5)


Open to ideas here...

**Comment by jaymcp** [comment]
we should get rid of the duotone options for sure. good shout.

**Comment by AmnestyAM** [comment]
@jaymcp same ticket if we can do today, another ticket if we can't.

**Comment by jaymcp** [comment]
@AmnestyAM PR is in, and @Gentyspun will review today. hopefully we can get it through the pipeline and over to you soon

**Comment by jaymcp** [comment]
@AmnestyAM duotone removal is now up on STG

**Comment by jaymcp** [comment]
it's pulling the full list from theme.json, yeah. which includes colours like twitter's blue and suchlike.
