### ISSUE TITLE
Bug - Index template with header / hero block 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#272]
**Describe the bug**  
There is a large content area inserted under the header / hero block and above the filter UI 

![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/8c38c5d0-96cc-4540-a9c1-72e23b672af0)

**To Reproduce**  
1. Visit https://wordpresstheme.amnesty.org/notifications/ 

**Expected behavior**  
A much smaller gap 

**Actual behavior**  
There was a big gap 
**Link to a page where the bug is reproduced in isolation (optional)**

**Comment by jaymcp** [comment]
editing the page, letting the blocks update, and then saving fixes this issue.
this suggests that the old header was being rendered, as well as an empty new hero.
the new hero should only render if there is data _to_ render, so i'm not sure what the cause is here

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/275

**Comment by AmnestyAM** [comment]
not sure how to test this, I will approve anyway
