### ISSUE TITLE
Bug - Search template shows a map sometimes when search query contains page 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#273]
**Describe the bug**  
Search template shows a map when search query contains "page"

**To Reproduce**  
1. Go to https://wordpresstheme.amnesty.org/search/y%20page%20y/ 

**Expected behaviour**  
no to be shown a map
like this https://wordpresstheme.amnesty.org/search/not%20a%20page%20here/  

**Actual behavior**  
A map is shown 

**Link to a page where the bug is reproduced in isolation (optional)**  
https://wordpresstheme.amnesty.org/search/search%20page/
https://wordpresstheme.amnesty.org/search/page/ 

**Screenshots**  
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/1994ec09-bdb6-433a-9815-61f7551523af)

**Comment by jaymcp** [comment]
This may no longer be an issue post-release of v2 of the theme

**Comment by BBTomA** [comment]
Issue resolved
