### ISSUE TITLE
Bug - mobile / responsive design does not seem to be applied 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#276]
**Describe the bug**  
Bug - mobile / responsive design does not seem to be applied 

**To Reproduce**  
1. Get a mobile
2. Go to anyweb page
3. See desktop version of the site

**Expected behaviour**  
mobile design 

**Actual behaviour**  
desktop design 

**Link to a page where the bug is reproduced in isolation (optional)**  
URL so we can quickly see the issue 

**Screenshots**  
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/d510b557-ce34-4b02-aed2-2bfd76670cfc)

**Comment by AmnestyAM** [comment]
LGTM feel free to release as a hot fix if that works for you, if not we can roll out in the next version

**Comment by AmnestyAM** [comment]
sounds good, thanks

**Comment by jaymcp** [comment]
This has been deployed.
