### ISSUE TITLE
Bug - 404 template - contains pop in test content 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#277]
**Describe the bug**  
404 template contains pop in test content 

**To Reproduce**  
1. Go to https://fa.amnesty.org/edvvdvbsgbsgb
2. See error

**Expected behaviour**  
No placeholder content 

**Actual behaviour**  
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/531ebe92-01a1-4ed9-9d15-9bed1096cabd)

**Additional context**

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/283

**Comment by AmnestyAM** [comment]
LGTM
