### ISSUE TITLE
Enhancement - Post List Block - Add background image support in list view mode

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#278]
**Describe the bug**  
Post List Block - Object selection backend UI not loading

**To Reproduce**  
1. Create a post
2. Add post list block 
3. choose object selection
4. choose list view

**Expected behaviour**  
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/c828a9be-9301-4113-b05c-08d6b9171d84)
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/36da26d9-5c79-49ff-b775-5301ceeedbe1)

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/292

**Comment by jaymcp** [comment]
Marking this as an enhancement, as list view mode has never had background image support.

**Comment by AmnestyAM** [comment]
I think I messed up a little on this ticket, sorry! 

It was the editor I had the issue with, as the editor showed the wrong UI that had the icons for adding images which it should not have had, this is now not an issue as I see the below for editing posts.

![Image](https://github.com/user-attachments/assets/4a691558-18c3-4cdb-90e0-c96793f3ce98)

I see we now render the featured image on the list block, which looks promising to me. 

https://isaidotorgstg.wpengine.com/en/testing-278-images-on-post-list-view/

I think if we were to keep this style below...

![Image](https://github.com/user-attachments/assets/79616a68-dc39-4308-a0d2-b31c7fe27306)

Then we would need the text too look like the below...

![Image](https://github.com/user-attachments/assets/51f4a982-dd47-49c0-92ef-bd1327633b49)

@Khartzenberg @SophieAmnesty @carolinejcourtney @daveamnesty @jaymcp @Gentyspun what do you all think?

**Comment by AmnestyAM** [comment]
I think this can be closed, the object selection user interface is now showing on STG and PRD (it was not showing previously (I think)) so my guess is I either miss tested and reported a false bug, or the issue self resolved. 

The way the text renders in the front end would not be approvable as it is,  so  I think its easier just to close this one and not release anything related to this ticket, what do you think @jaymcp ?

**Comment by AmnestyAM** [comment]
Also no one replied so I dont think anyone is fussed either way

**Comment by jaymcp** [comment]
I'm happy to go with whatever you prefer, @AmnestyAM, just let me know.

**Comment by AmnestyAM** [comment]
closing no longer required, thanks, and sorry for the confusing ticket

**Comment by jaymcp** [comment]
no worries, @AmnestyAM!
