### ISSUE TITLE
Epic - Migrate SCSS variables to core WordPress theme.json CSS variables 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#286]
### Sprints allocated 
Number of sprints: one
Link to sprint if known: TBC
https://learn.wordpress.org/tutorial/introduction-to-theme-json 

## Goals 
- Improve consistency between humanity (black & white) and Amnesty Brand plugin (block, while & color)
- Allows Humanity to be recolored easily
- Makes the theme more contestant with the way WordPress builds their themes  
- To support all current core setup

## Tasks
- [ ] #334
- [x] #335
- [x] #336
- [x] #337
- [x] #366
- [x] #367

## Think about (optional)
- Tickets for translations
- Tickets for content

**Comment by jaymcp** [comment]
i think #334 is worth keeping open separately, as it's more likely to be an ongoing process, and can perhaps be its own epic. therefore i'm closing this epic as complete.
