### ISSUE TITLE
Migrate custom card custom block to custom card pattern 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#287]
https://wordpresstheme.amnesty.org/blocks/b014-action/

- Group
- grey background
- heading
- image
- paragraph
- button

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/309

**Comment by AmnestyAM** [comment]
The caption looks weird, might need to flag this in training
![image](https://github.com/user-attachments/assets/7f127545-f2c6-49be-acc1-f867219d1109)

![image](https://github.com/user-attachments/assets/0531e16c-1de9-4ded-bbed-3ce566576d91)


Also the alignment control dont seem to do anything, might also be another training thing, unless you have thoughts @Gentyspun  or @jaymcp 

![image](https://github.com/user-attachments/assets/d5b2080b-dcb0-4be2-8163-1bcdbcdd9878)

**Comment by AmnestyAM** [comment]
also what are you thoughts about the width? I was kind of expecting it to fill the horizontal space and then be constrained by the column it was in, but looks like we have a max width, I am not opposed to this just wanted your thoughts? Will this approach work well for this pattern being added into our sidebar and or 1/3 or 1/4 layouts?

![image](https://github.com/user-attachments/assets/964c0966-3c7d-46bd-9573-662d4038c412)

![image](https://github.com/user-attachments/assets/fcf2ea31-c1b9-4ad2-a8d0-a7f4acf1384d)

Alignment, in the CMS it looks centered in the CMS when alignment is set to none, in the front end the card is bigger 480px wide and left aligned.

Alignment, in the CMS is left aligned in the CMS when set to 1468 in the CMS. The card is smaller in the front end at 350px. 

Let me know your thoughts.

**Comment by AmnestyAM** [comment]
PS I might still pass this as its probably not blocking, just wanted your thoughts too

**Comment by AmnestyAM** [comment]
one other thing...

I still see the option to add the Custom Card Custom block (as well as the pattern).

I also don't see the custom block converting to the pattern here -> https://isaidotorgstg.wpengine.com/en/wp-admin/post.php?post=211890&action=edit

**Comment by Gentyspun** [comment]
Hey @AmnestyAM 

I have a few notes/questions about your comments.

The image caption is just an issue with padding so I can fix that easily just adding padding to either side of the caption.

In regards to alignment, currently there is no alignment options only width (Normal and Wide), which is in line with how the block used to work. I'm happy to change this, but just wanted to clarify what you think is best for the pattern. So here are a couple of options:

- Remove the wide/normal option and have the block just fill whatever container it is inside, and then add left, centre, right alignment options
- Keep the wide/normal options and add alignment options as well, but this will mean the pattern will not automatically fill whatever container it is in.

Currently the normal and wide options just work with a max-width on the group I believe.

**Comment by AmnestyAM** [comment]
I think to fill the space is better then have someone use columns. We will tell people not to add a card in a page or post without columns, it should be used in columns or in a sidebar. 

Thanks,

**Comment by Gentyspun** [comment]
> I think to fill the space is better then have someone use columns. We will tell people not to add a card in a page or post without columns, it should be used in columns or in a sidebar.
> 
> Thanks,

PRs for custom card to fill it's container
Theme: https://github.com/amnestywebsite/humanity-theme/pull/475
Branding Plugin: https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/53

**Comment by AmnestyAM** [comment]
@Gentyspun are we going to be able to close this one off soon?

**Comment by AmnestyAM** [comment]
@jaymcp @Gentyspun this looks good, what do you think about the image height, on a card I would have expect the aspect ratio to be fixed what are you thoughts though? 

![image](https://github.com/user-attachments/assets/7191d87c-415e-4cdb-ae70-33b0ef699ccf)

**Comment by AmnestyAM** [comment]
PS is there a transform in pace to migrate the old blocks to the new patterns?

**Comment by jaymcp** [comment]
a fixed aspect ratio may be possible; i will take a look at the feasibility.

as far as automatic transformation… i don't think there is one, no. we can do so in a new ticket, if desirable; but i think that it may cause some visual oddities under some circumstances because the pattern will now stretch to fill its container, unlike the block.

**Comment by jaymcp** [comment]
@AmnestyAM yes, we can set a fixed aspect ratio on the image within the pattern. there's a few we can choose from (see below screenshot), but 16:9 is probably the best fit for most scenarios. what do you think?
![](http://bigbite.im/i/2NSueb+)

**Comment by AmnestyAM** [comment]
16:9 sounds good to me. No worries about the transform, we can look at another ticket if needed. thanks

**Comment by jaymcp** [comment]
PRs are in for that

https://github.com/amnestywebsite/humanity-theme/pull/512
https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/56

**Comment by jaymcp** [comment]
@AmnestyAM the aspect ratio change is now up on STG. note that only new insertions of the pattern will show the change

**Comment by AmnestyAM** [comment]
perfecto
![image](https://github.com/user-attachments/assets/1b1bff26-0b84-4658-947e-daa01aa7f00b)
