### ISSUE TITLE
Migrate call to action custom block to call to action pattern

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#288]
https://wordpresstheme.amnesty.org/blocks/b003-call-to-action/

- group 
- top and bottom border block styles
- heading 
- button

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/310

**Comment by AmnestyAM** [comment]
I still see the option to add the Custom Card Custom block (as well as the pattern). 

I also don't see the custom block converting to the pattern here -> https://isaidotorgstg.wpengine.com/en/wp-admin/post.php?post=211890&action=edit

**Comment by AmnestyAM** [comment]
Looks good to me 

https://isaidotorgstg.wpengine.com/en/testing-call-to-action/

I was still able to access the old block, and what will we do about transforming the data from the custom block to the pattern?

**Comment by jaymcp** [comment]
The transformation work was done in https://github.com/amnestywebsite/humanity-theme/issues/364
This is currently on DEV awaiting testing, which I hope to complete today

**Comment by jaymcp** [comment]
The transform is now available to test on UAT.
I'm not sure where the branch is that hides the CTA block from the inserter... I'll try to find it. However, I do have a separate PR in to move our recently-deprecated blocks to the deprecated directory (an oversight), which will also hide the CTA block from the inserter, so if I can't find it, we do have an alternative https://github.com/amnestywebsite/humanity-theme/pull/390

**Comment by AmnestyAM** [comment]
transform worked :-) thanks
