### ISSUE TITLE
Bug - Hero block - Featured video not displaying

### ISSUE THREAD

**Issue by daveamnesty** [amnestywebsite/humanity-theme#312]
**Describe the bug**  
A video that has been added to the hero block in the back office is not showing on the front end. 

**To Reproduce**  
Steps to reproduce the behaviour:
1. Go to https://www.amnesty.org/en/careers/
2. The hero block video at the top of the page does not load
3. In the back office you can see that the video has been added to the hero block, so it should show

**Expected behaviour**  
The video should display on the front end

**Actual behaviour**  
The video does not load

**Screenshots**  
![image](https://github.com/user-attachments/assets/1fcc20dd-570e-4218-867c-29c345599e9f)
![image](https://github.com/user-attachments/assets/4499afea-f3bb-4a56-9b3e-7e2c2aa9377a)

**Platform:**  
https://www.whatsmybrowser.org/b/C45F9

**Comment by Gentyspun** [comment]
Hi @daveamnesty, I logged into PROD to take a look at this and it looks like the video in question is a GIF, which is not supported in the `<video>` tag

<img width="295" alt="Screenshot 2024-09-23 at 12 44 51" src="https://github.com/user-attachments/assets/361a1963-0604-4514-8417-859b9ac25dfa">

**Comment by daveamnesty** [comment]
Looks like the content might have also changed since I logged this.

**Comment by BBTomA** [comment]
Closed, content issue explained and resolved
