### ISSUE TITLE
Nav block - Style core WP nav block

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#316]
Re-enable the core/navigation block and style to match the current custom menu block.

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/344

**Comment by AmnestyAM** [comment]
@jaymcp 
our in content in page nav will not work with WP nave as it would replace the main top nav.

We will need two Nav blocks the WP top main FSE nav block, and... 
Amnesty custom in page in content nav block 

We need to re lable tickets and re label blocks
