### ISSUE TITLE
Nav block - Transform current custom nav to core nav

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#317]
Write a function to find and replace all custom menu blocks with core/navigation blocks while retaining the contents, attributes and styles

**Comment by Gentyspun** [comment]
After further investigation and extensive testing, it appears automatic conversion may not be possible.

We would need to add the entire block library as a dependancy and re-write how some of the core/navigation block functions into functional components.

**Comment by AmnestyAM** [comment]
I am guessing the title on this was a typo and this is not about the quote block - I guess we can run content query and do this manually for the nav block
