### ISSUE TITLE
Bug - Image - Copyright field overhangs the picture

### ISSUE THREAD

**Issue by SophieAmnesty** [amnestywebsite/humanity-theme#323]
**Describe the bug**  
When an image is smaller than the container (e.g. column) it's in. The grey copyright field extends to fit the container and creates a sort of overhanging line. 

**To Reproduce**  
1. Add new post
2. Insert small image 
3. Preview and see that when the image is smaller than the column the copyright field overhangs. 

**Expected behaviour**  
the copyright field should be the same width as the image 

**Actual behaviour**  
The copyright field is wider than the image. 

**Link to a page where the bug is reproduced in isolation (optional)**  
https://isaidotorgstg.wpengine.com/en/latest/news/2024/07/test-image-copyright-overhang/ 

**Screenshots**  
![image](https://github.com/user-attachments/assets/e7e6ba6e-d2e3-46f9-827a-6ba190b0e51c)

**Platform:**  
https://www.whatsmybrowser.org/b/X0NLV

**Additional context**  
workaround is to center align the image or make the image bigger.

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/401

**Comment by AmnestyAM** [comment]
I get this error 
![image](https://github.com/user-attachments/assets/0aba192e-803e-4db5-9128-756a9e879d66)

here https://isaidotorgstg.wpengine.com/en/wp-admin/post.php?post=211527&action=edit

So not sure if the fix is ok or not

**Comment by jaymcp** [comment]
This is due to a change in the way captions are handled in WP 6.6.
I have a fix for this in PR now. Sorry for the troub.e

**Comment by jaymcp** [comment]
@AmnestyAM this fix is now on STG

**Comment by AmnestyAM** [comment]
LGTM 
![image](https://github.com/user-attachments/assets/cca5b360-223b-425a-bb60-934c203c92e1)
