### ISSUE TITLE
On the sidebar when blocks are added they should have consistent widths and alignment 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#33]
**Describe the bug**  
On the sidebar blocks added should have consistent widths

**To Reproduce**  
1. Create a side bar 
2. Add a recently added block
3. Add a CTA block
4. view widths of blocks in the side bar 

**Expected behaviour**  
expect the blocks fill the space in the side bar so they align on both the left and right 

**Actual behaviour**  
The blocks align on the left but not the right 

**Link to a page where the bug is reproduced in isolation (optional)**  
https://isaidotorgstg.wpengine.com/en/latest/news/2023/09/saudi-arabia-migrants-workers-who-toiled-in-amazon-warehouses-are-victims-of-trafficking-v3/ 

**Screenshots**  
 ![image](https://github.com/amnestywebsite/amnesty-wp-theme/assets/37809410/9eae8e17-57fa-4c3e-8e54-4b1a3ce2cc79)

**Platform:**  
Paste link from here https://www.whatsmybrowser.org/ 

**Additional context**  

from https://github.com/amnestywebsite/internal/issues/100#issuecomment-1744656778

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/112

**Comment by AmnestyAM** [comment]
@SophieAmnesty an FYI here this may have an adverse effect on pages using recently add in the main content area, I think this is an edge case and should be avoided anyway but feel free to let me know if you know of the recently added block being used on a full width page in the page content.
