### ISSUE TITLE
Enhancement — Details Block — Add HTML anchor support

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#333]
https://isaidotorgstg.wpengine.com/en/latest/news/2024/06/gallery-block-test/

Details block is cool, but any chance we can extend that to have this functionality
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/b593564b-ed97-4674-8e98-bd0488058ec4)

_Originally posted by @AmnestyAM in https://github.com/amnestywebsite/humanity-theme/issues/124#issuecomment-2194867709_

**Comment by AmnestyAM** [comment]
LGTM FYI @SophieAmnesty 

https://isaidotorgstg.wpengine.com/en/latest/news/2024/08/details-test/

![Image](https://github.com/user-attachments/assets/c782e2ef-c976-475d-91a0-fd04ba4e55f4)
