### ISSUE TITLE
Epic - Look through the brand guidelines to identify what can be added to the theme.json

### ISSUE THREAD

**Issue by BBTomA** [amnestywebsite/humanity-theme#334]

**Comment by mikachan** [comment]
Just dropping a link to the brand guidelines: https://brandhub.amnesty.org/

**Comment by mikachan** [comment]
**Making a note of some initial thoughts:**

Potential theme.json settings that may benefit content editors using the theme:
- Spacing size presets ([Example](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L164))
- Font size presets ([Example](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L253))
- Defining all available fonts so they're visible in the Editor ([Example](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L200))
- Define typography settings (line height, letter spacing, font weight, etc) ([Example](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L905))
- Specific settings and styles for Core blocks ([Example](https://github.com/WordPress/twentytwentyfour/blob/trunk/theme.json#L305))

All of these are probably controlled with custom CSS at the moment and each of these might provide a way to split up the work for https://github.com/amnestywebsite/humanity-theme/issues/286.

We could also create style variations for the different colour palettes and maybe the campaign colour palettes mentioned in the brand guidelines. I've opened an example PR, just to show how these are set up alongside the existing theme.json file: https://github.com/amnestywebsite/humanity-theme/pull/338

**Comment by jaymcp** [comment]
This is great information, thanks for collating it!

**Comment by BBTomA** [comment]
@jaymcp closed, feel free to re-open
