### ISSUE TITLE
On the Social icons block the styling has changed and is no longer on brand 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#36]
**Describe the bug**  
On the Social icons block the styling has changed and is no longer on brand 

**To Reproduce**  
1. Add a page
2. Add social icons 
5. We dont have a screen shot :-( 
6. https://web.archive.org/web/20200222173941/https://www.amnesty.org/en/get-involved/ 

**Expected behaviour**  
They should have padding and use the theme default not WP animation animations

**Actual behaviour**  
we lost our styles 

**Link to a page where the bug is reproduced in isolation (optional)**  
https://www.amnesty.org/en/get-involved/

**Screenshots**  
https://web.archive.org/web/20200222173941/https://www.amnesty.org/en/get-involved/
https://wordpresstheme.amnesty.org/blocks/b018-social-icons/

**Comment by Gentyspun** [comment]
Created a PR on the theme to remove the branding block styles and a PR on the branding plugin to add them back in. 
Theme PR fixes margin and transform styles from original ticket.

Theme PR: https://github.com/amnestywebsite/humanity-theme/pull/97
Plugin PR: https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/7

**Comment by AmnestyAM** [comment]
Looks like the buttons moved position was that expected?


![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/cf2eabcc-5a54-4944-88ca-ca31bc1c2acc)

https://www.amnesty.org/en/get-involved/
https://isaidotorgstg.wpengine.com/en/get-involved/

**Comment by jaymcp** [comment]
Ah, looks like the wrapper is missing the alignment attribute FYI @Gentyspun

**Comment by AmnestyAM** [comment]
LGTM on STG also LGTM on PRD which is a little strange but fine.
