### ISSUE TITLE
Bug -Scheduled posts - Not working in Arabic

### ISSUE THREAD

**Issue by SophieAmnesty** [amnestywebsite/humanity-theme#368]
**Describe the bug**  
A user of the Arabic site (on amnesty.org) has reported that Arabic posts are not publishing automatically when scheduled: 

> "when we schedule anything for publishing on wordpress, it doesn't publish automatically. On the day of publishing we go back and do it manually. Any idea what could be the problem? "

I have just tested this on staging and not managed to reproduce. Will try to find out more information. Putting in a ticket anyway just in case anyone else hears of something similar happening / has more information. I've asked the user to let me know the next time they have a post scheduled so I can check it's properly set up.

**Comment by SophieAmnesty** [comment]
Apparently a scheduled post worked fine for the user today, so maybe just user error on previous occasions... 

I will close the issue as it seems like we don't really have a problem. Sorry for this pointless ticket!

**Comment by AmnestyAM** [comment]
no worries :-)
