### ISSUE TITLE
Epic - Post modernization Bug Scrub 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#397]
After a long time of updating to WordPress 6.6 and modernizing the theme its time to srub some bugs, let's see how many of the 58 bugs we can close! :-) 

@Gentyspun This one is for you, which @jaymcp is looking after the upcoming releases etc. 

### Sprints allocated 
Number of sprints: one

## Goals    
- Reduce bugs count across repos
- https://github.com/amnestywebsite/humanity-theme/issues?q=is%3Aopen+is%3Aissue+label%3Abug 39 bugs 
- https://github.com/amnestywebsite/humanity-petitions/issues?q=is%3Aissue+is%3Aopen+label%3Abug 2 bugs
- https://github.com/amnestywebsite/amnesty-wp-theme/issues?q=is%3Aissue+is%3Aopen+label%3ABug 17 bugs 
- replies to these https://github.com/amnestywebsite/wp-plugin-petitions/issues

**Comment by AmnestyAM** [comment]
@Gentyspun bonus imaginary points for squashing LRC bugs :-) 
https://github.com/orgs/amnestywebsite/projects/3/views/30

**Comment by BBTomA** [comment]
@jaymcp closed, feel free to re-open
