### ISSUE TITLE
Bug - font sizes forcing headers to exceed site width on smaller devices

### ISSUE THREAD

**Issue by BBTomA** [amnestywebsite/humanity-theme#403]
The headers on the sites need media quires adding to allow the font sizes to be responsive. Currently the font sizes aren't changing meaning that the font exceeds the width of the site on smaller devices.

![Image](https://github.com/user-attachments/assets/ee8a0fb5-e7e2-427e-aa9b-2bdb6b328d19)

**Comment by jaymcp** [comment]
@AmnestyAM the fix for this should be available to test on STG now
