### ISSUE TITLE
Bug - Post Template - Disable Sidebar and Maximise Content toggles not working

### ISSUE THREAD

**Issue by carolinejcourtney** [amnestywebsite/humanity-theme#450]
**Describe the bug**  
When the 'Disable Sidebar' and 'Maximise content' toggles in the Appearance sidebar are selected, the content still appears with the default layout with the sidebar present and smaller content width 

**Expected behaviour**  

**Actual behaviour**  
![Image](https://github.com/user-attachments/assets/2e02739d-daa8-43b6-bd05-2b30d270d52e)

![Image](https://github.com/user-attachments/assets/b046c6c6-c3ab-4dd3-82c3-893e9b5e2724)

https://www.amnesty.org/en/latest/news/2024/10/human-rights-ranking-electric-vehicle-industry/

https://www.whatsmybrowser.org/b/LP0KM

**Comment by jaymcp** [comment]
A fix for this is now available on DEV for testing

**Comment by carolinejcourtney** [comment]
Thank you - all approved :)
