### ISSUE TITLE
Release Candidate - Hotfix v2.0.5

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#453]
## Tickets slated for release  
- https://github.com/amnestywebsite/humanity-theme/issues/449
- https://github.com/amnestywebsite/humanity-theme/issues/450
- https://github.com/amnestywebsite/humanity-theme/issues/454

## Automated tests  
- [x] GhostInspector tests run as expected
- [ ] New GhostInspector tests tickets created (if needed)

## Version number  
- Theme: `v2.0.5`

## Scheduled release date  
- Thursday 24th October 2024

**Comment by carolinejcourtney** [comment]
this is good to move to PRD this afternoon :) - thanks @jaymcp

**Comment by jaymcp** [comment]
#454 has been added to the RC for rollout in this release.

**Comment by jaymcp** [comment]
release complete. slack thread (internal): https://bigbite.slack.com/archives/CBLHK14G7/p1729763157108999
