### ISSUE TITLE
Bug - Menu Block - Missing top and bottom padding/margins 

### ISSUE THREAD

**Issue by carolinejcourtney** [amnestywebsite/humanity-theme#457]
**Describe the bug**  
If you find a page with an existing inpage menu, the padding or margins on the top and bottom of the block seem to be missing. It looks like this issue only occurs for menus which have enough items to require the arrows to appear (more than 3 items). If there are only 3 menu items then the correct style appears. 

Incorrect style - 
![image](https://github.com/user-attachments/assets/ae6b9e0d-2205-4169-94dd-0bd614a4e6f4)
https://www.amnesty.org/en/what-we-do/discrimination/racial-justice/

Correct Style
![image](https://github.com/user-attachments/assets/91e70d01-a7a8-4d4d-9d7f-967f78275bda)
https://www.amnesty.org/en/what-we-do/armed-conflict/

**Platform:**  
 https://www.whatsmybrowser.org/b/LP0KM

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/461

**Comment by AmnestyAM** [comment]
LGTM
