### ISSUE TITLE
Bug - post template - page title not showing on some posts

### ISSUE THREAD

**Issue by SophieAmnesty** [amnestywebsite/humanity-theme#470]
**Describe the bug**  
posts that use the hero block rather than just the featured image at the top don't seem to be showing their page titles at the moment. 

**To Reproduce**  
1. create new post
2. add page title 
3. add hero block and featured image 
4. save and preview 
5. see no page title visible on the page 

**Expected behaviour**  
page title should always be visible on posts.

**Actual behaviour**  
no page title on posts using hero block.

**Link to a page where the bug is reproduced in isolation (optional)**  
have reproduced **on production in a draft** here's the preview link: 
https://www.amnesty.org/en/?p=219482&preview=true&_thumbnail_id=219441 

I've tried to reproduce the issue on staging but I'm having a different issue which is that the hero block isn't showing. 
https://isaidotorgstg.wpengine.com/en/latest/news/2024/11/this-is-the-post-title/

**Platform:**  
https://www.whatsmybrowser.org/b/UILZ7

**Additional context**  
examples: 
- https://www.amnesty.org/en/latest/news/2024/09/israel-opt-israeli-military-must-be-investigated-for-war-crime-of-wanton-destruction-in-gaza-new-investigation/ 
- https://www.amnesty.org/en/latest/news/2024/10/human-rights-ranking-electric-vehicle-industry/
- https://www.amnesty.org/en/latest/news/2024/08/ecuador-gas-flares-amazon-threatens-human-rights-present-and-future/

**Comment by jaymcp** [comment]
@SophieAmnesty the reason that the hero was not being output on STG was because the template had been edited in the site editor. I've reset the template, and now your test post on STG reflects the same issue as PRD

**Comment by SophieAmnesty** [comment]
Ohhh I see, thank you Jay. I will remove that post from production now then, thanks!

**Comment by jaymcp** [comment]
@SophieAmnesty fix should now be on STG. CC @AmnestyAM

**Comment by SophieAmnesty** [comment]
Wonderful, looks good to me, thank you @jaymcp

**Comment by AmnestyAM** [comment]
happy to roll out a hot fix, thanks

**Comment by jaymcp** [comment]
@SophieAmnesty the fix for this has now been deployed to PRD in [`v2.0.8`](https://github.com/amnestywebsite/humanity-theme/releases/tag/v2.0.8)

**Comment by SophieAmnesty** [comment]
Phewwww. THANKYOUUU!!
