### ISSUE TITLE
Bug - zh.amnesty.org - can only add one tag per post

### ISSUE THREAD

**Issue by SophieAmnesty** [amnestywebsite/humanity-theme#474]
**Describe the bug**  
A user has reported having difficulty adding more than one tag to posts on the [Chinese site](https://zh.amnesty.org/). 

**To Reproduce**  
1. create a new post
2. add several tags 
3. save and preview 
4. See only one tag 
5. return to editor - only one tag is still checked. 

**Expected behaviour**  
users should be able to add multiple tags to their posts. 

**Actual behaviour**  
only one tag saved onto the post.

**Link to a page where the bug is reproduced in isolation (optional)**  
https://ischinesestg.wpengine.com/topic/justice-systems/test/ 

**Platform:**  
https://www.whatsmybrowser.org/b/UILZ7

**Additional context**  
I noticed their link setup is different - they have the tags in the url. don't suppose it could be something to do with that?

**Comment by AmnestyAM** [comment]
@SophieAmnesty @jaymcp will correct me if I am wrong but I think thats due to a feature on .org that you cant be both, research and news and impact etc? When they migrate in they will have the same taxonomies etc

**Comment by SophieAmnesty** [comment]
Ahh ok, so any of the sites still using multiple lists of terms within the Content Type taxonomy are going to need to change to multiple separate taxonomies. 

I've had a look through the sites this morning, I think the sites would be the Chinese and Persian IS sites (which would be good prep for site migration into to .org anyway) and then Ghana, Nigeria, Philippines and Zimbabwe. https://oneamnesty.sharepoint.com/sites/AISFNCWebDevelopment/referencedocuments/Taxonomy%20Audit%20-%20IS%20Hosted%20Sites.xlsx?d=w710e9862e6d5469c8aedb102ec1d28a7&csf=1&web=1&e=eFcGQj

**Comment by jaymcp** [comment]
Sorry for the late reply on this; not sure how I missed it. 

It seems that, for some reason, the inability to tag a post with more than one category is a bug triggered by the branding plugin.
In the plugin, we remove block patterns that aren't ours (e.g. WooCommerce, Yoast, etc.) to reduce noise in the editor, and provide a better experience for the editors. 
However it seems that, in unregistering those patterns, somehow WP can no longer load in the full list of terms assigned to the post in the editor.

This makes absolutely no sense to me whatsoever, but at least I have a starting point to figure out a solution.
