### ISSUE TITLE
Bug - secmoroccoprd - featured image not showing on posts

### ISSUE THREAD

**Issue by SophieAmnesty** [amnestywebsite/humanity-theme#485]
**Describe the bug**  
When a user publishes a post with a featured image, it doesn't show on the page. 
It does show in thumbnails. 
The **hide featured image** setting is off. 

**To Reproduce**  
1. add new post
2. add featured image
3. publish 
4. view post, see no image 

**Expected behaviour**  
Featured image should be visible at the top of the post when it's been added. 

**Actual behaviour**  
Can't see any featured image on the page. 

**Link to a page where the bug is reproduced in isolation (optional)**  
https://secmoroccoprd.wpenginepowered.com/monde-ce-quil-faut-savoir-au-sujet-du-sommet-sur-le-climat-cop29/
https://secmoroccoprd.wpenginepowered.com/israel-et-territoire-palestinien-occupe-la-loi-interdisant-lunrwa-est-une-criminalisation-de-laide-humanitaire/ 

**Screenshots**  
![catpure d'ecran](https://github.com/user-attachments/assets/ad24c40b-45b1-4a9d-9a24-80015488fdeb)
![catpure d'ecran 2](https://github.com/user-attachments/assets/94788877-8c32-4233-89a1-6b9790b19611)
![catpure d'ecran 3](https://github.com/user-attachments/assets/9c0e0ded-a76d-45e9-9d13-b4d33862860b)
 
**Platform:**  
https://www.whatsmybrowser.org/b/UILZ7

**Comment by AmnestyAM** [comment]
Hey @SophieAmnesty it looks like they deleted the header pattern

```
<!-- wp:amnesty-core/pop-in /-->

<!-- wp:amnesty-core/site-header /-->
```

![image](https://github.com/user-attachments/assets/2a3f63cf-fe99-456c-910d-68316112a848)

as it now says 

```
<!-- currently unused /-->

```

here https://secmoroccoprd.wpenginepowered.com/wp-admin/site-editor.php?postType=wp_template_part&postId=humanity-theme%2F%2Fheader&canvas=edit

Thanks

**Comment by SophieAmnesty** [comment]
closing as fixed. user had also edited the single post template which I have now restored to default theme settings.
