### ISSUE TITLE
Epic - Core WP Update - Enhanced FSE Features (Block conversion)

### ISSUE THREAD

**Issue by jaymcp** [amnestywebsite/humanity-theme#6]
All issues tracked here -> 

Full site editing brings with it a new paradigm for block registration. Whereas previously blocks could be entirely crafted with JavaScript, or as a combination of JavaScript and PHP, FSE now enforces the latter. 

This means that blocks that are entirely crafted using JavaScript are no longer visible in the editor, and will need converting to use the new registration methodology.

### Epic and sprint owner
tbc

### Sprints allocated 
Number of sprints: 2
Link to sprint if known: TBC

## Goals 
- Add Full Site Editing support for "old" blocks

### Tickets
- [x] #141
- [x] #142
- [x] #143
- [x] #144
- [x] #145
- [x] #146
- [x] #147
- [x] #148

**Comment by jaymcp** [comment]
PR created to update the Branding plugin to support FSE: https://github.com/amnestywebsite/wp-plugin-amnesty-branding/pull/15 - FYI @Gentyspun

**Comment by jaymcp** [comment]
This was merged to DEV this morning! 🎉

**Comment by AmnestyAM** [comment]
would be good if /header was an alias for /hero 

The hero block error makes the page fail 

https://isaidotorgstg.wpengine.com/en/latest/news/2024/06/test-for-6/

**Comment by AmnestyAM** [comment]
going to pass as all the other blocks load just fine

**Comment by jaymcp** [comment]
> would be good if /header was an alias for /hero

You should be able to type any of `header`, `banner`, or `hero` to select the Hero block
