### ISSUE TITLE
On the slider block remove 100% width

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#8]
**Describe the bug**  
When the slider block is added to the homepage it occupies 100% of the page width

**To Reproduce**  
1. Go to EU site
2. zoom out
3. Notice the slider is taking up 100% of the width

**Expected behaviour**  
The content should not break out past the menu or footer 

**Actual behaviour**  
The content breaks out past the menu and footer and goes to the edges of the page

**Link to a page where the bug is reproduced in isolation (optional)**  
https://www.amnesty.eu/latest-news/
https://wordpresstheme.amnesty.org/blocks/b006-timeline-slider/

**Screenshots**  
![image](https://github.com/amnestywebsite/amnesty-wp-theme/assets/37809410/21fd9016-4f29-48b4-b34b-528c12b08966)

**Comment by Gentyspun** [comment]
PR Created: https://github.com/amnestywebsite/humanity-theme/pull/96

**Comment by AmnestyAM** [comment]
LGTM here https://isaidotorgstg.wpengine.com/en/
