### ISSUE TITLE
On the header block adding bold in the title remove a space 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#9]
**Describe the bug**  
On the header block adding bold in the title remove a space 

**To Reproduce**  
1. Add a page
2. Add a header block
3. Some words and make on bold in the title

**Expected behaviour**  
There should be a space between each word 

**Actual behaviour**  
A space is missing between the words 

**Screenshots**  
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/41518257-53bd-4043-a789-16dbcaf24481)

**Platform:**  
Paste link from here https://www.whatsmybrowser.org/ 

**Additional context**  
https://github.com/amnestywebsite/amnesty-wp-theme/issues/1751

**Comment by AmnestyAM** [comment]
https://isaidotorgstg.wpengine.com/en/header-bold-test/


![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/79daadf4-eaf5-4a64-9618-b1849378dcac)


maybe its because I press control B while selecting the text?

**Comment by AmnestyAM** [comment]
no defo broken https://isaidotorgstg.wpengine.com/en/latest/news/2024/06/bold-hero-test-2/

**Comment by jaymcp** [comment]
Yeah that's our fault, sorry. We mistakenly used `esc_html` for the title and content fields, instead of `wp_kses*`. There's a fix for that incoming. I'll update the ticket status once it's deployed

**Comment by AmnestyAM** [comment]
LGTM
