### ISSUE TITLE
On the dashboard when looking at the "appearance" "themes" options the theme screen shot is not loading 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#91]
**Describe the bug**  

**To Reproduce**  
1. Go /wp-admin/themes.php
2. See image not loaded 

**Expected behaviour**  
The theme image should be shown 

**Actual behaviour**  
No image is shown 

**Link to a page where the bug is reproduced in isolation (optional)**  
/wp-admin/themes.php

**Screenshots**  
![image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/6f4f2c3d-413c-4680-bd78-2e7fd5222fbf)

**Comment by Gentyspun** [comment]
Created PR: https://github.com/amnestywebsite/humanity-theme/pull/94

**Comment by AmnestyAM** [comment]
would be cool to get this out by the talk I am doing on Thursday (if possible)

**Comment by jaymcp** [comment]
@AmnestyAM i've merged this to STG, so should be ready for UAT in approx 5 mins

**Comment by AmnestyAM** [comment]
LGTM 
![Uploading image.png…]()
